apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ds389.secretName" . }}
  labels:
    {{- include "ds389.labels" . | nindent 4 }}
type: Opaque
data:
  DS_DM_PASSWORD: {{ default (randAlphaNum 19 | nospace) .Values.secret.defaultPassword.dm | b64enc | quote }}
  DS_REPL_PASSWORD: {{ default (randAlphaNum 19 | nospace) .Values.secret.defaultPassword.repl | b64enc | quote }}