---
apiVersion: v1
kind: Service
metadata:
  name: artds-lb
  labels:
    app.kubernetes.io/name: &name artds
    app.kubernetes.io/instance: &instance 389ds
    app.kubernetes.io/version: &version v3.1
  annotations:
    metallb.io/loadBalancerIPs: 192.168.218.181
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: *name
    app.kubernetes.io/instance: *instance
    app.kubernetes.io/version: *version
  ports:
    - port: 3389
      name: ldap-tcp
      targetPort: ldap-tcp
      protocol: TCP
    - port: 3636
      name: ldaps-tcp
      targetPort: ldaps-tcp
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: artds-0
  labels:
    app.kubernetes.io/name: &name artds
    app.kubernetes.io/instance: &instance 389ds
    app.kubernetes.io/version: &version v3.1
    statefulset.kubernetes.io/pod-name: artds-0
  annotations:
    metallb.io/loadBalancerIPs: 192.168.218.182
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: *name
    app.kubernetes.io/instance: *instance
    app.kubernetes.io/version: *version
  ports:
    - port: 3389
      name: ldap-tcp
      targetPort: ldap-tcp
      protocol: TCP
    - port: 3636
      name: ldaps-tcp
      targetPort: ldaps-tcp
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: artds-1
  labels:
    app.kubernetes.io/name: &name artds
    app.kubernetes.io/instance: &instance 389ds
    app.kubernetes.io/version: &version v3.1
    statefulset.kubernetes.io/pod-name: artds-1
  annotations:
    metallb.io/loadBalancerIPs: 192.168.218.183
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: *name
    app.kubernetes.io/instance: *instance
    app.kubernetes.io/version: *version
  ports:
    - port: 3389
      name: ldap-tcp
      targetPort: ldap-tcp
      protocol: TCP
    - port: 3636
      name: ldaps-tcp
      targetPort: ldaps-tcp
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: artds
  labels:
    app.kubernetes.io/name: &name artds
    app.kubernetes.io/instance: &instance 389ds
    app.kubernetes.io/version: &version v3.1
spec:
  selector:
    app.kubernetes.io/name: *name
    app.kubernetes.io/instance: *instance
    app.kubernetes.io/version: *version
  ports:
    - port: 3389
      name: ldap-tcp
      targetPort: ldap-tcp
      protocol: TCP
    - port: 3636
      name: ldaps-tcp
      targetPort: ldaps-tcp
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: artds-headless
  labels:
    app.kubernetes.io/name: &name artds
    app.kubernetes.io/instance: &instance 389ds
    app.kubernetes.io/version: &version v3.1
spec:
  clusterIP: None
  selector:
    app.kubernetes.io/name: *name
    app.kubernetes.io/instance: *instance
    app.kubernetes.io/version: *version
  ports:
    - port: 3389
      name: ldap-tcp
      targetPort: ldap-tcp
      protocol: TCP
    - port: 3636
      name: ldaps-tcp
      targetPort: ldaps-tcp
      protocol: TCP
