{{- if .Values.jobs.infra.enable }}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "artds.fullname" . }}-infra
  labels:
    {{- include "artds.labels" . | nindent 4 }}
spec:
  template:
    spec:
      restartPolicy: Never
      volumes:
        - name: infra
          configMap:
            name: {{ include "artds.fullname" . }}-job-infra
      containers:
      - name: ds
        image: {{ .Values.jobs.infra.image.repository }}:{{ .Values.jobs.infra.image.tag }}
        imagePullPolicy: {{ .Values.jobs.infra.image.pullPolicy }}
        {{- with .Values.jobs.infra.resources }}
        resources:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        env:
          - name: DS_HL_SVC_NAME
            value: "{{ include "artds.fullname" . }}-headless"
          - name: DS_POD_NAME
            value: "{{ include "artds.fullname" . }}"
          - name: DS_SVC_PORT
            # value: {{ .Values.services.main.port | quote }}
            value: "3389"
        envFrom:
          - secretRef:
              {{- if .Values.ds.adminSecretName }}
              name: {{ .Values.ds.adminSecretName }}
              {{- else }}
              name: {{ include "artds.fullname" . }}
              {{- end }}
        volumeMounts:
          - name: infra
            mountPath: '/etc/openldap/init'
        command: [ '/bin/bash', '-ce' ]
        args:
          - |
            logMsg() {
                echo "{\"date\":\"$(date "+%d/%m/%Y %T%z")\",\"facility\":\"$1\",\"message\":\"$2\"}"
            }
            until dsconf ldap://${DS_POD_NAME}-0.${DS_HL_SVC_NAME}:${DS_SVC_PORT} -D 'cn=Directory Manager' -w "${DS_DM_PASSWORD}" backend suffix list > /dev/null 2>&1; do
              sleep 1
              TRIALS=$(( TRIALS + 1 ))
              if [ $TRIALS -gt 60 ]; then logMsg ERROR "Can't connect to ds server" && exit 1; fi
            done
            # TODO: контроль наличия ACI
            ldapmodify -c -H ldap://${DS_POD_NAME}-0.${DS_HL_SVC_NAME}:${DS_SVC_PORT} -D "cn=Directory Manager" \
            -w "${DS_DM_PASSWORD}" -f /etc/openldap/init/init-config-modify.ldiff
            ldapadd -c -H ldap://${DS_POD_NAME}-0.${DS_HL_SVC_NAME}:${DS_SVC_PORT} -D "cn=Directory Manager" \
            -w "${DS_DM_PASSWORD}" -f /etc/openldap/init/init-config.ldiff
{{- end }}