{{- if and .Values.monitoring.enabled (eq .Values.monitoring.scrapingMethod "servicemonitor") .Values.monitoring.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "artds.fullname" . }}-metrics
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "artds.labels" . | nindent 4 }}
    component: monitoring
    {{- with .Values.monitoring.serviceMonitor.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "artds.selectorLabels" . | nindent 6 }}
      component: monitoring
  endpoints:
    - port: metrics
      interval: {{ .Values.monitoring.serviceMonitor.interval }}
      scrapeTimeout: {{ .Values.monitoring.serviceMonitor.scrapeTimeout }}
      path: /metrics
      scheme: http
      {{- with .Values.monitoring.serviceMonitor.relabelings }}
      relabelings:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
